const languages = [
  "basic",
  "python",
  "java",
  "kotlin",
  "dart",
  "html",
  "css",
  "js",
  "ts",
  "c",
  "csharp",
  "haskell",
  "javafx",
  "python_tkinter",
  "git",
];
const fullName = {
  "basic": "Computer Basic",
  "python": "Python",
  "java": "Java",
  "kotlin": "Kotlin",
  "dart": "Dart",
  "html": "HTML",
  "css": "CSS",
  "js": "Javascript",
  "ts": "Typescript",
  "c": "C",
  "csharp": "C#",
  "haskell": "Haskell",
  "python_tkinter": "Python Tkinter",
  "javafx": "JavaFX",
  "git": "Git & Github",
};
