const Map<int, String> topics = {
  1: "Introduction to Java Programming",

  2: "Array, Conditional and Looping",

  3: "Class and Object",

  4: "Object Oriented Programming",

  5: "Exceptions Handling",

  6: "Multi-Threading",

  7: "Collections Framework",

  8:
      "Working with File"
      "Module 8 Test",

  9: "Tutorial Test for All Modules",
};
const Map<int, Map<int, String>> modules = {
  1: {
    1: "Installing Java Development Kit",
    2: "Installing IntelliJ IDE",
    3: "Variable and Data type",
    4: "Integer Data Types (byte, short, int, long)",
    5: "Java Comments, Floating, Character and Boolean Data Type",
    6: "Arithmetic Operators",
    7: "Assignment Operators",
    8: "Unary Operators",
    9: "Relational Operators",
    10: "Logical Operators",
    11: "Ternary Operator",
    12: "String class",
    13: "Request Input with Scanner",
  },
  2: {
    14: "Array",
    15: "Create Array from String",
    16: "Multi-Dimensional Array",
    17: "Conditional Statement",
    18: "If Conditional Statement - 1",
    19: "If Conditional Statement - 2",
    20: "Switch Conditional Statement",
    21: "Looping",
    22: "While Loop",
    23: "Do While Loop",
    24: "For Loop",
    25: "Enhanced For Loop",
    26: "Nested If",
    27: "Nested For",
    28: "String Useful Methods",
    29: "String Replace Method",
    30: "String to int",
  },
  3: {
    31: "Create a Class",
    32: "Creating Instances from Class and Call its Attributes",
    33: "Methods",
    34: "Method Return Type",
    35: "Method Parameters",
    36: "Method Overloading",
    37: "Constructor",
    38: "Global vs Local Variables",
    39: "Java Packages",
  },
  4: {
    40: "Access Modifiers",
    41: "Encapsulation",
    42: "Inheritance",
    43: "Polymorphism",
    44: "Up-casting vs Down-casting",
    45: "Type Casting between String and Primitive Data Types",
    46: "Abstraction and Abstract Class",
    47: "Interface",
    48: "Abstract Class vs Interface",
    49: "Static Keyword",
    50: "Math Class",
    51: "Final Keyword",
    52: "Sealed Class",
    53: "Nested Inner Class",
    54: "Static Inner Class",
    55: "Method Local Inner Class",
    56: "Anonymous Inner Class",
    57: "Record",
    58: "Enumeration",
    59: "Singleton Object",
  },
  5: {
    60: "Java Exceptions",
    61: "Exceptions Handling with Try - Catch",
    62: "Exceptions Handling with Throws",
    63: "Throw New Exception",
  },
  6: {
    64: "Multi-Threaded Programming",
    65: "Extending Thread Class",
    66: "Implementing Runnable Interface",
    67: "Join Thread",
    68: "Thread Synchronization",
  },
  7: {
    69: "Introduction to Collections Framework",
    70: "Generic Class and Generic Method",
    71: "List Interface and Array List",
    72: "Vector",
    73: "Stack",
    74: "Linked List",
    78: "Map Interface and Hash Map",
    79: "Linked Hash Map",
    80: "Tree Map",
    81: "Set Interface Module",
  },
  8: {
    75: "Read File from Text",
    76: "Write File to Text",
    77: "Notepad Project",
  },
};
final Map<int, Lesson> lessons = {
  1: Lesson(1, 1, "https://youtu.be/fFwFlLj9Dxc"),
  2: Lesson(1, 2, "https://youtu.be/hN_hGLuaTfc"),
  3: Lesson(1, 3, "https://youtu.be/\\_osMwaaivws"),
  4: Lesson(1, 4, "https://youtu.be/ZzF708Le5xk"),
  5: Lesson(1, 5, "https://youtu.be/IqjBmb1E8Lg"),
  6: Lesson(1, 6, "https://youtu.be/CSduNT-meME"),
  7: Lesson(1, 7, "https://youtu.be/g8YpkS57E2I"),
  8: Lesson(1, 8, "https://youtu.be/f0W1zWVpuws"),
  9: Lesson(1, 9, "https://youtu.be/EMDes1PFveg"),
  10: Lesson(1, 10, "https://youtu.be/WYkfUf5-I-4"),
  11: Lesson(1, 11, "https://youtu.be/03T6oRTs_I0"),
  12: Lesson(1, 12, "https://youtu.be/0sBWuMAtwFc"),
  13: Lesson(2, 13, "https://youtu.be/mACF8UqFEIs"),
  14: Lesson(2, 14, "https://youtu.be/2aIZgzyumU4"),
  15: Lesson(2, 15, "https://youtu.be/f3KQ_-QO4iA"),
  16: Lesson(2, 16, "https://youtu.be/kXU66J_VyZk"),
  17: Lesson(2, 17, "https://youtu.be/sAxXfndlAzk"),
  18: Lesson(2, 18, "https://youtu.be/skVI_6mmIwQ"),
  19: Lesson(2, 19, "https://youtu.be/K-V8Kr0o8NQ"),
  20: Lesson(2, 20, "https://youtu.be/aUl8zq5knGA"),
  21: Lesson(2, 21, "https://youtu.be/eoQ9gHLANVE"),
  22: Lesson(2, 22, "https://youtu.be/IvoZyklMpRk"),
  23: Lesson(2, 23, "https://youtu.be/vPLehgSFeY0"),
  24: Lesson(2, 24, "https://youtu.be/ZRHrp0Ui5L8"),
  25: Lesson(2, 25, "https://youtu.be/N0rb1fdppUY"),
  26: Lesson(2, 26, "https://youtu.be/XR32hyhoqhw"),
  27: Lesson(2, 27, "https://youtu.be/2QDhsVM_RS4"),
  28: Lesson(2, 28, "https://youtu.be/cntv3KkAQHs"),
  29: Lesson(2, 29, "https://youtu.be/GsQAO-JXe7s"),
  30: Lesson(2, 30, "https://youtu.be/mACF8UqFEIs"),
  31: Lesson(3, 31, "https://youtu.be/drRSofShJzE"),
  32: Lesson(3, 32, "https://youtu.be/aeJQFNzidK0"),
  33: Lesson(3, 33, "https://youtu.be/QO8y-M9kE1g"),
  34: Lesson(3, 34, "https://youtu.be/bEyFIsuLfQU"),
  35: Lesson(3, 35, "https://youtu.be/nQy7w93OIwE"),
  36: Lesson(3, 36, "https://youtu.be/pqDKNdZt0cU"),
  37: Lesson(3, 37, "https://youtu.be/H9F3phdXxt0"),
  38: Lesson(3, 38, "https://youtu.be/UJ-NQPXxv1k"),
  39: Lesson(3, 39, "https://youtu.be/pzZxfQoUle8"),
  40: Lesson(4, 40, "https://youtu.be/XYsMx6HLMXc"),
  41: Lesson(4, 41, "https://youtu.be/sF1VA8ZJnD4"),
  42: Lesson(4, 42, "https://youtu.be/jpgUMx3q3lM"),
  43: Lesson(4, 43, "https://youtu.be/ZUJ5nwQR70k"),
  44: Lesson(4, 44, "https://youtu.be/Wksac4aHcnE"),
  45: Lesson(4, 45, "https://youtu.be/mqkkdVFu9E0"),
  46: Lesson(4, 46, "https://youtu.be/GRuATUQEjEE"),
  47: Lesson(4, 47, "https://youtu.be/fL9Iy0U-bdg"),
  48: Lesson(4, 48, "https://youtu.be/FBPLJg_TMrA"),
  49: Lesson(4, 49, "https://youtu.be/zjkeM-7fx_A"),
  50: Lesson(4, 50, "https://youtu.be/X_cLm0oXMqs"),
  51: Lesson(4, 51, "https://youtu.be/Fl_Pzr7hJv0"),
  52: Lesson(4, 52, "https://youtu.be/ZvMoZ8Buz7g"),
  53: Lesson(4, 53, "https://youtu.be/Bofvx8qUFuA"),
  54: Lesson(4, 54, "https://youtu.be/bU9fyfjthnQ"),
  55: Lesson(4, 55, "https://youtu.be/MVl4P13dEbI"),
  56: Lesson(4, 56, "https://youtu.be/8jnFVJKlCwE"),
  57: Lesson(4, 57, "https://youtu.be/Z6kVChio0TQ"),
  58: Lesson(4, 58, "https://youtu.be/7Qt4OI8rW4A"),
  59: Lesson(4, 59, "https://youtu.be/tuXdw2wQ3Yc"),
  60: Lesson(5, 60, "https://youtu.be/RC6ExYJJdFI"),
  61: Lesson(5, 61, "https://youtu.be/auHAau0OsSg"),
  62: Lesson(5, 62, "https://youtu.be/Hmz_yiYos0Q"),
  63: Lesson(5, 63, "https://youtu.be/7-EDyeqHEo4"),
  64: Lesson(6, 64, "https://youtu.be/r7J9_4CTlD0"),
  65: Lesson(6, 65, "https://youtu.be/TAmMb59xRSA"),
  66: Lesson(6, 66, "https://youtu.be/4Sea-\\_ZErIc"),
  67: Lesson(6, 67, "https://youtu.be/sGY7Gihzp0c"),
  68: Lesson(6, 68, "https://youtu.be/7-EDyeqHEo4"),
};

class Lesson {
  final int moduleId;
  final int id;
  final String youtubeLink;

  Lesson(this.moduleId, this.id, this.youtubeLink);
}
