// TOPIC SECTION (Module 1 - Introduction)
const Map<int, String> javaTopics = {
  1: "Introduction to Java Programming",

  2: "Array, Conditional and Looping",

  3: "Class and Object",

  4: "Object Oriented Programming",

  5: "Exceptions Handling",

  6: "Multi-Threading",

  7: "Collections Framework",

  8:
      "Working with File"
      "Module 8 Test",
};
const Map<int, String> pythonTopics = {
  1: "Introduction to Python",
  2: "Built-in Data Types",
  3: "Python Operators",
  4: "Statements",
  5: "Functions",
  6: "Modules, Classes and Objects",
  7: "File input and output",
  8: "Web Requests in Python",
};
const Map<int, String> basicTopics = {
  1: "The Machine", // Hardware: CPU, RAM, Storage
  2: "The Data", // Binary, Bits, Bytes, and Files
  3: "The Manager", // Operating Systems & File Systems
  4: "The Command Line", // Talking to the computer with text
  5: "The Interface", // Browsers, Software, and the Web
  6: "The Connected World", // Networking, IP Addresses, and DNS
  7: "The AI Partner", // Using Gemini/ChatGPT/Copilot
};
const Map<int, String> htmlTopics = {
  1: "The Skeleton", // Structure: <!DOCTYPE>, <html>, <head>, <body>
  2: "The Semantics", // Meaning: <header>, <nav>, <main>, <section>, <footer>
  3: "The Scribe", // Text: Typography, Headings, <p>, <strong>, <em>
  4: "The Navigator", // Links: Hyperlinks <a> and Navigation Logic
  5: "The Collector", // Data: Lists <ul>, <ol> and Tables <table>
  6: "The Input", // Interaction: Forms <form>, <input>, and Labels
  7: "The Publisher", // Deployment: GitHub & Vercel
};
const Map<int, String> dartTopics = {
  1: "Introduction to Dart & Development Environment Setup",
  2: "Variables, Built-in Data Types, and Type Inference",
  3: "Operators, Expressions, and String Interpolation",
  4: "Control Flow: If-Else, Switch, and Loops (For, While)",
  5: "Functions: Parameters, Return Types, and Lexical Scope",
  6: "Collections: Lists, Sets, and Maps with Generics",
  7: "OOP I: Classes, Objects, and Constructors",
  8: "OOP II: Encapsulation, Getters, and Setters",
  9: "OOP III: Inheritance, Abstract Classes, and Interfaces",
  10: "OOP IV: Mixins, Extensions, and Enum Classes",
  11: "Sound Null Safety: Nullable Types and Null-aware Operators",
  12: "Error Handling: Exceptions, Try-Catch, and Custom Errors",
  13: "Asynchronous Programming: Futures, Async, and Await",
  14: "Reactive Programming: Streams and Sinks",
  15: "Dart Packages, Libraries, and Project Architecture",
};
const Map<String, Map<int, String>> topics = {
  "java": javaTopics,
  "python": pythonTopics,
  "basic": basicTopics,
  "html": htmlTopics,
  "dart": dartTopics,
};

// MODULE SECTION (Module 1: Lesson 1, Lesson 2)
const Map<int, Map<int, String>> javaModules = {
  1: {
    1: "Installing Java Development Kit",
    2: "Installing IntelliJ IDE",
    3: "Variable and Data type",
    4: "Integer Data Types (byte, short, int, long)",
    5: "Java Comments, Floating, Character and Boolean Data Type",
    6: "Arithmetic Operators",
    7: "Assignment Operators",
    8: "Unary Operators",
    9: "Relational Operators",
    10: "Logical Operators",
    11: "Ternary Operator",
    12: "String class",
    13: "Request Input with Scanner",
  },
  2: {
    14: "Array",
    15: "Create Array from String",
    16: "Multi-Dimensional Array",
    17: "Conditional Statement",
    18: "If Conditional Statement - 1",
    19: "If Conditional Statement - 2",
    20: "Switch Conditional Statement",
    21: "Looping",
    22: "While Loop",
    23: "Do While Loop",
    24: "For Loop",
    25: "Enhanced For Loop",
    26: "Nested If",
    27: "Nested For",
    28: "String Useful Methods",
    29: "String Replace Method",
    30: "String to int",
  },
  3: {
    31: "Create a Class",
    32: "Creating Instances from Class and Call its Attributes",
    33: "Methods",
    34: "Method Return Type",
    35: "Method Parameters",
    36: "Method Overloading",
    37: "Constructor",
    38: "Global vs Local Variables",
    39: "Java Packages",
  },
  4: {
    40: "Access Modifiers",
    41: "Encapsulation",
    42: "Inheritance",
    43: "Polymorphism",
    44: "Up-casting vs Down-casting",
    45: "Type Casting between String and Primitive Data Types",
    46: "Abstraction and Abstract Class",
    47: "Interface",
    48: "Abstract Class vs Interface",
    49: "Static Keyword",
    50: "Math Class",
    51: "Final Keyword",
    52: "Sealed Class",
    53: "Nested Inner Class",
    54: "Static Inner Class",
    55: "Method Local Inner Class",
    56: "Anonymous Inner Class",
    57: "Record",
    58: "Enumeration",
    59: "Singleton Object",
  },
  5: {
    60: "Java Exceptions",
    61: "Exceptions Handling with Try - Catch",
    62: "Exceptions Handling with Throws",
    63: "Throw New Exception",
  },
  6: {
    64: "Multi-Threaded Programming",
    65: "Extending Thread Class",
    66: "Implementing Runnable Interface",
    67: "Join Thread",
    68: "Thread Synchronization",
  },
  7: {
    69: "Introduction to Collections Framework",
    70: "Generic Class and Generic Method",
    71: "List Interface and Array List",
    72: "Vector",
    73: "Stack",
    74: "Linked List",
    75: "Map Interface and Hash Map",
    76: "Linked Hash Map",
    77: "Tree Map",
    78: "Set Interface Module",
  },
  8: {
    79: "Read File from Text",
    80: "Write File to Text",
    81: "Notepad Project",
  },
};
const Map<int, Map<int, String>> pythonModules = {
  1: {
    1: "What is Python",
    2: "Installing Python",
    3: "Run Python on Terminal",
    4: "Running python as a python program",
    5: "Installing PyCharm Community Edition",
    6: "Running Hello World with Pycharm",
    7: "Python Comments",
    8: "Variable in Python",
  },
  2: {
    9: "Python Basic Data Types",
    10: "Boolean Type",
    11: "Numeric Types",
    12: "String Type",
    13: "Python Casting",
    14: "None Type",
    15: "List Type",
    16: "Tuple Type",
    17: "Dictionary Type",
    18: "Set Type",
    19: "Set Operations",
  },
  3: {
    20: "Python Operators",
    21: "Arithmetic Operators",
    22: "Assignment Operators",
    23: "Comparison Operators",
    24: "Logical Operators",
    25: "Identity Operators",
    26: "Membership Operators",
    27: "Operator Precedence",
  },
  4: {
    28: "If conditional statement",
    29: "Match conditional statement",
    30: "While loop statement",
    31: "For loop statement",
    32: "try: except: statement",
    33: "Raise an exception",
  },
  5: {
    34: "Functions",
    35: "Function arguments",
    36: "Returning values",
    37: "User Input",
    38: "Python Lambda",
    39: "Scope",
  },
  6: {
    40: "Module in Python",
    41: "Variables in module",
    42: "Renaming a module",
    43: "from import module",
    44: "Class and Object",
    45: "Methods",
    46: "The __init__() method",
    47: "The __str__() method",
    48: "Inheritance",
    49: "Polymorphism",
    50: "Operator Polymorphism",
    51: "Function Polymorphism",
    52: "Method Polymorphism",
  },
  7: {
    53: "File Input/Output",
    54: "Read a file",
    55: "Create or Write to a file",
    56: "Delete a file or folder",
  },
  8: {
    57: "What is an api?",
    58: "Installing and importing requests dependency",
    59: "Getting a random joke",
    60: "Understanding JSON",
    61: "Joke and Cat Fact Generator",
  },
};
const Map<int, Map<int, String>> basicModules = {
  1: {
    1: "The Cycle: Input, Process, and Output",
    2: "The CPU: The Brain of the Machine",
    3: "RAM: The Digital Workspace",
    4: "Storage: Hard Drives vs. SSDs",
    5: "The Motherboard: The Nervous System",
    6: "The Transistor: The On/Off Switch",
  },
  2: {
    7: "Binary: How Computers Count with 1s and 0s",
    8: "Bits and Bytes: Measuring Digital Information",
    9: "Text and Strings: How Computers Read Your Name",
    10: "Numbers and Logic: Integers vs. Decimals",
    11: "Colors and Pixels: How Images Work",
    12: "Files and Formats: How Data is Packaged",
  },
  3: {
    13: "The OS: The Boss of the System",
    14: "Kernel vs. Shell: The Core and the Interface",
    15: "File Systems: How the Manager Organizes Storage",
    16: "Processes & Threads: How the OS Multitasks",
    17: "Memory Management: Protecting the RAM",
    18: "User Accounts & Permissions: Security and Privacy",
    19: "Drivers: The OS Language Translators",
  },
  4: {
    20: "The CLI: Why Text is More Powerful than Icons",
    21: "Terminal vs. Shell: Command Prompt & PowerShell",
    22: "Navigation: Moving Through Folders (cd, dir)",
    23: "File Operations: Creating and Deleting (mkdir, type, del)",
    24: "Paths: Absolute vs. Relative (Where am I?)",
    25: "Networking Tools: Testing Connection (ping, ipconfig)",
    26: "Permissions: Running as Administrator",
  },
  5: {
    27: "GUI: Using Pictures instead of Code",
    28: "Windows & Icons: The 'Desktop' Metaphor",
    29: "The Browser: Your Door to the Internet",
    30: "Software vs. Apps: What’s the difference?",
    31: "How Software is Built: The 'Look' and the 'Brain'",
    32: "Update & Version: Why does software change?",
    33: "Accessibility: Software for Everyone",
  },
  6: {
    34: "What is a Network? (Nodes and Links)",
    35: "IP Addresses: The Phone Numbers of the Internet",
    36: "DNS: The Phonebook (How google.com becomes an IP)",
    37: "WiFi vs. Mobile Data: How your phone connects", // Added
    38: "The Journey: From your Phone to a Global Website", // Added
    39: "Censorship: How Governments block websites", // Added
    40: "VPNs: The Secret Tunnel to Freedom", // Added
    41: "HTTP/HTTPS: The Rules of the Web",
    42: "The Cloud: It’s Just Someone Else’s Computer",
  },
  7: {
    43: "What is AI? (The Machine that Learns)",
    44: "Generative AI: How Gemini and ChatGPT 'Talk'",
    45: "Prompt Engineering: How to give good instructions",
    46: "The Hallucination: Why AI sometimes lies",
    47: "AI Ethics & Safety: What NOT to share with AI",
    48: "The Future: Living with your AI Partner",
  },
};
const Map<int, Map<int, String>> htmlModules = {
  1: {
    1: "The Doctype: Declaring the Version",
    2: "The HTML Tag: The Root and Lang Attributes",
    3: "The Head: The Invisible Brain of the Page",
    4: "The Meta Charset: Unlocking Shan Script (UTF-8)",
    5: "The Title: Giving Your Book a Name",
    6: "The Body: Where the Content Lives",
    7: "Comments: Leaving Notes for the Scribe",
    8: "The Meta Viewport: Making it Mobile-Ready",
  },
  2: {
    9: "Semantic Layout: Using Header and Nav",
    10: "Main and Section: Organizing Chapters",
    11: "Articles: Independent Pieces of Content",
    12: "Aside: Adding Marginalia and Notes",
    13: "Footer: The Colophon and Copyright",
    14: "The Div Tag: The Generic Container",
    15: "The Span Tag: Targeting Small Text Segments",
  },
  3: {
    16: "Hierarchy: H1 through H6",
    17: "The Paragraph: Writing in Shan Blocks",
    18: "Strong vs. Bold: Importance vs. Appearance",
    19: "Em vs. Italic: Stress vs. Style",
    20: "Underline and Strikethrough Tags",
    21: "Line Breaks and Horizontal Rules",
    22: "Preformatted Text and Code Snippets",
    23: "Blockquotes: Citing External Wisdom",
    24: "Superscript and Subscript",
  },
  4: {
    25: "The Anchor Tag: Creating Hyperlinks",
    26: "Relative vs. Absolute Paths (Linking Modules)",
    27: "The Target Attribute: Control How Links Open",
    28: "ID Attributes: Linking to Sections on One Page",
    29: "The Download Attribute: Sharing Files",
    30: "Email and Phone Links (mailto and tel)",
    31: "Building a Navigation Menu in Pure HTML",
  },
  5: {
    32: "The Image Tag: src, alt, and title",
    33: "Image Sizing and Aspect Ratios",
    34: "The Video Tag: Bringing the Page to Life",
    35: "The Audio Tag: Adding Music and Voices",
    36: "Figure and Figcaption: Labeling Media",
    37: "The Picture Element: Responsive Image Sources",
    38: "Embedding Iframes: Maps and External Content",
  },
  6: {
    39: "Unordered Lists: Creating Bullet Points",
    40: "Ordered Lists: Step-by-Step Instructions",
    41: "Description Lists: Terms and Definitions",
    42: "Tables: Rows, Headers, and Data Cells",
    43: "Table Caption, Thread, Tbody, and Tfoot",
    44: "Forms: Creating the Input Field",
    45: "Labels, Fieldsets, and Legends",
    46: "Input Types: Text, Password, and Email",
    47: "The Textarea: For Long Shan Descriptions",
  },
  7: {
    48: "W3C Validation: Checking for Broken Ink",
    49: "The Favicon: Adding a Digital Seal to the Tab",
    50: "SEO Basics: Meta Descriptions and Open Graph",
    51: "GitHub: Uploading the Manuscript Folder",
    52: "Vercel: Connecting and Zero-Config Deploy",
    53: "Custom Domains: Naming Your Digital Library",
    54: "Performance Check: Optimizing Assets for Speed",
  },
};
const Map<int, Map<int, String>> dartModules = {
  1: {
    // Intro & Setup
    1: "What is Dart? (JIT vs AOT)",
    2: "The Dart SDK & Runtime Environment",
    3: "Setting up the IDE (VS Code / Android Studio)",
    4: "Creating your first Console App",
    5: "The main() function & Basic Syntax",
    6: "Comments and Documentation Best Practices",
  },
  2: {
    // Variables & Types
    7: "Variable Declaration: Type vs Name",
    8: "Numbers: int and double",
    9: "Strings and Booleans",
    10: "Type Inference with 'var'",
    11: "The 'dynamic' type: When to use it",
    12: "Constants: final vs const",
    13: "Type Conversion (Parsing & Casting)",
  },
  3: {
    // Operators & Expressions
    14: "Arithmetic and Assignment Operators",
    15: "Equality and Relational Operators",
    16: "Logical Operators (&&, ||, !)",
    17: "Type Test Operators (is, as)",
    18: "String Interpolation & Multi-line Strings",
    19: "Operator Precedence and Expressions",
  },
  4: {
    // Control Flow
    20: "The If-Else Statement",
    21: "Conditional Expressions (Ternary ? :)",
    22: "Switch Statements & Patterns (Dart 3.0)",
    23: "Standard For Loops",
    24: "While and Do-While Loops",
    25: "For-in and forEach Basics",
    26: "Break and Continue",
  },
  5: {
    // Functions
    27: "Defining and Calling Functions",
    28: "Return Types and the void keyword",
    29: "Positional Parameters (Required vs Optional)",
    30: "Named Parameters and {required}",
    31: "Default Parameter Values",
    32: "Arrow Syntax (=>)",
    33: "Lexical Scope and Variable Lifetime",
    34: "Introduction to Anonymous Functions",
    35: "Higher-Order Functions",
  },
  6: {
    // Collections
    36: "Lists: Indexing and Growable Lists",
    37: "Essential List Methods (add, remove, sort)",
    38: "Sets: Unique Values and Set Math",
    39: "Maps: Key-Value Pairs",
    40: "Generics <T> for Type Safety",
    41: "Spread Operators (...) and Collection If",
    42: "Transforming Collections (map, where, toList)",
  },
  7: {
    // OOP I: Classes & Constructors
    43: "Classes: Blueprints for Objects",
    44: "Instance Variables and Fields",
    45: "Methods and 'this' keyword",
    46: "The Default Constructor",
    47: "Parameterized and Named Constructors",
    48: "Initializer Lists",
    49: "Constant Constructors (Flutter Optimization)",
    50: "Factory Constructors",
  },
  8: {
    // OOP II: Encapsulation
    51: "Privacy with the Underscore (_)",
    52: "Creating Getters for Controlled Reading",
    53: "Creating Setters for Validation",
    54: "Computed Properties",
    55: "The 'late' keyword in Classes",
    56: "Final vs Private Fields",
  },
  9: {
    // OOP III: Inheritance & Abstracts
    57: "Inheritance: The 'extends' keyword",
    58: "The 'super' keyword",
    59: "Method Overriding and @override",
    60: "Abstract Classes: Rules and Usage",
    61: "Abstract Methods",
    62: "Implementing Interfaces",
    63: "Polymorphism in Action",
  },
  10: { // OOP IV: Mixins & Enums
    64: "Mixins: Code Reuse with 'with'",
    65: "Extension Methods on Existing Types",
    66: "Basic Enums for State",
    67: "Enhanced Enums with Fields (Dart 3.0)",
    68: "Comparing Mixins vs Inheritance",
  },
  11: {
    // Null Safety
    68: "The Principle of Null Safety",
    69: "Nullable Types (?)",
    70: "The Null-aware Operator (?.)",
    71: "The If-Null Operator (??)",
    72: "Null-aware Assignment (??=)",
    73: "The Bang (!) Operator: When to avoid it",
    74: "Type Promotion and Flow Analysis",
  },
  12: {
    // Error Handling
    75: "Exceptions vs Errors",
    76: "Try-Catch Blocks",
    77: "Catching Specific Exceptions with 'on'",
    78: "The Finally Clause",
    79: "Throwing Exceptions Manually",
    80: "Creating Custom Exception Classes",
  },
  13: {
    // Async Programming
    81: "The Event Loop Concept",
    82: "Futures: States and Results",
    83: "Using .then() vs async/await",
    84: "The 'await' keyword and pausing",
    85: "Handling Async Errors with try-catch",
    86: "Future.wait() for Parallel Tasks",
    87: "Future.delayed() and Timeouts",
  },
  14: {
    // Reactive (Streams)
    88: "What is a Stream?",
    89: "Single Subscription vs Broadcast",
    90: "The .listen() method and Subscriptions",
    91: "StreamControllers and Sinks",
    92: "Async Generators (async* and yield)",
    93: "Transforming Streams (map/where)",
    94: "Closing Streams and Memory Leaks",
  },
  15: {
    // Packages & Project
    95: "The pubspec.yaml File",
    96: "Importing Local and External Packages",
    97: "Library Visibility and 'export'",
    98: "Introduction to Unit Testing",
    99: "Dart CLI: format and analyze",
    100: "Capstone: Final Logic Integration",
  },
};

const Map<String, Map<int, Map<int, String>>> modules = {
  "java": javaModules,
  "python": pythonModules,
  "basic": basicModules,
  "dart": dartModules,
  "html": htmlModules,
};

// LESSON SECTION (Lesson 1: Content)
final Map<int, Lesson> pythonLessons = {
  1: Lesson(1, 1),
  2: Lesson(1, 2),
  3: Lesson(1, 3),
  4: Lesson(1, 4),
  5: Lesson(1, 5),
  6: Lesson(1, 6),
  7: Lesson(1, 7),
  8: Lesson(1, 8),
  9: Lesson(2, 9),
  10: Lesson(2, 10),
  11: Lesson(2, 11),
  12: Lesson(2, 12),
  13: Lesson(2, 13),
  14: Lesson(2, 14),
  15: Lesson(2, 15),
  16: Lesson(2, 16),
  17: Lesson(2, 17),
  18: Lesson(2, 18),
  19: Lesson(2, 19),
  20: Lesson(3, 20),
  21: Lesson(3, 21),
  22: Lesson(3, 22),
  23: Lesson(3, 23),
  24: Lesson(3, 24),
  25: Lesson(3, 25),
  26: Lesson(3, 26),
  27: Lesson(3, 27),
  28: Lesson(4, 28),
  29: Lesson(4, 29),
  30: Lesson(4, 30),
  31: Lesson(4, 31),
  32: Lesson(4, 32),
  33: Lesson(4, 33),
  34: Lesson(5, 34),
  35: Lesson(5, 35),
  36: Lesson(5, 36),
  37: Lesson(5, 37),
  38: Lesson(5, 38),
  39: Lesson(5, 39),
  40: Lesson(6, 40),
  41: Lesson(6, 41),
  42: Lesson(6, 42),
  43: Lesson(6, 43),
  44: Lesson(6, 44),
  45: Lesson(6, 45),
  46: Lesson(6, 46),
  47: Lesson(6, 47),
  48: Lesson(6, 48),
  49: Lesson(6, 49),
  50: Lesson(6, 50),
  51: Lesson(6, 51),
  52: Lesson(6, 52),
  53: Lesson(7, 53),
  54: Lesson(7, 54),
  55: Lesson(7, 55),
  56: Lesson(7, 56),
  57: Lesson(8, 57),
  58: Lesson(8, 58),
  59: Lesson(8, 59),
  60: Lesson(8, 60),
  61: Lesson(8, 61),
};
final Map<int, Lesson> javaLessons = {
  1: Lesson(1, 1),
  2: Lesson(1, 2),
  3: Lesson(1, 3),
  4: Lesson(1, 4),
  5: Lesson(1, 5),
  6: Lesson(1, 6),
  7: Lesson(1, 7),
  8: Lesson(1, 8),
  9: Lesson(1, 9),
  10: Lesson(1, 10),
  11: Lesson(1, 11),
  12: Lesson(1, 12),
  13: Lesson(2, 13),
  14: Lesson(2, 14),
  15: Lesson(2, 15),
  16: Lesson(2, 16),
  17: Lesson(2, 17),
  18: Lesson(2, 18),
  19: Lesson(2, 19),
  20: Lesson(2, 20),
  21: Lesson(2, 21),
  22: Lesson(2, 22),
  23: Lesson(2, 23),
  24: Lesson(2, 24),
  25: Lesson(2, 25),
  26: Lesson(2, 26),
  27: Lesson(2, 27),
  28: Lesson(2, 28),
  29: Lesson(2, 29),
  30: Lesson(2, 30),
  31: Lesson(3, 31),
  32: Lesson(3, 32),
  33: Lesson(3, 33),
  34: Lesson(3, 34),
  35: Lesson(3, 35),
  36: Lesson(3, 36),
  37: Lesson(3, 37),
  38: Lesson(3, 38),
  39: Lesson(3, 39),
  40: Lesson(4, 40),
  41: Lesson(4, 41),
  42: Lesson(4, 42),
  43: Lesson(4, 43),
  44: Lesson(4, 44),
  45: Lesson(4, 45),
  46: Lesson(4, 46),
  47: Lesson(4, 47),
  48: Lesson(4, 48),
  49: Lesson(4, 49),
  50: Lesson(4, 50),
  51: Lesson(4, 51),
  52: Lesson(4, 52),
  53: Lesson(4, 53),
  54: Lesson(4, 54),
  55: Lesson(4, 55),
  56: Lesson(4, 56),
  57: Lesson(4, 57),
  58: Lesson(4, 58),
  59: Lesson(4, 59),
  60: Lesson(5, 60),
  61: Lesson(5, 61),
  62: Lesson(5, 62),
  63: Lesson(5, 63),
  64: Lesson(6, 64),
  65: Lesson(6, 65),
  66: Lesson(6, 66),
  67: Lesson(6, 67),
  68: Lesson(6, 68),
  69: Lesson(7, 69),
  70: Lesson(7, 70),
  71: Lesson(7, 71),
  72: Lesson(7, 72),
  73: Lesson(7, 73),
  74: Lesson(7, 74),
  75: Lesson(7, 75),
  76: Lesson(7, 76),
  77: Lesson(7, 77),
  78: Lesson(7, 78),
  79: Lesson(8, 79),
  80: Lesson(8, 80),
  81: Lesson(8, 81),
};
final Map<int, Lesson> basicLessons = {
  1: Lesson(1, 1),
  2: Lesson(1, 2),
  3: Lesson(1, 3),
  4: Lesson(1, 4),
  5: Lesson(1, 5),
  6: Lesson(1, 6),
  7: Lesson(2, 7),
  8: Lesson(2, 8),
  9: Lesson(2, 9),
  10: Lesson(2, 10),
  11: Lesson(2, 11),
  12: Lesson(2, 12),
  13: Lesson(3, 13),
  14: Lesson(3, 14),
  15: Lesson(3, 15),
  16: Lesson(3, 16),
  17: Lesson(3, 17),
  18: Lesson(3, 18),
  19: Lesson(3, 19),
  20: Lesson(4, 20),
  21: Lesson(4, 21),
  22: Lesson(4, 22),
  23: Lesson(4, 23),
  24: Lesson(4, 24),
  25: Lesson(4, 25),
  26: Lesson(4, 26),
  27: Lesson(5, 27),
  28: Lesson(5, 28),
  29: Lesson(5, 29),
  30: Lesson(5, 30),
  31: Lesson(5, 31),
  32: Lesson(5, 32),
  33: Lesson(5, 33),
  34: Lesson(6, 34),
  35: Lesson(6, 35),
  36: Lesson(6, 36),
  37: Lesson(6, 37),
  38: Lesson(6, 38),
  39: Lesson(6, 39),
  40: Lesson(6, 40),
  41: Lesson(6, 41),
  42: Lesson(6, 42),
  43: Lesson(7, 43),
  44: Lesson(7, 44),
  45: Lesson(7, 45),
  46: Lesson(7, 46),
  47: Lesson(7, 47),
  48: Lesson(7, 48),
};
final Map<int, Lesson> dartLessons = {
  1: Lesson(1, 1),
  2: Lesson(1, 2),
  3: Lesson(1, 3),
  4: Lesson(1, 4),
  5: Lesson(1, 5),
  6: Lesson(1, 6),
  7: Lesson(2, 7),
  8: Lesson(2, 8),
  9: Lesson(2, 9),
  10: Lesson(2, 10),
  11: Lesson(2, 11),
  12: Lesson(2, 12),
  13: Lesson(2, 13),
  14: Lesson(3, 14),
  15: Lesson(3, 15),
  16: Lesson(3, 16),
  17: Lesson(3, 17),
  18: Lesson(3, 18),
  19: Lesson(3, 19),
  20: Lesson(4, 20),
  21: Lesson(4, 21),
  22: Lesson(4, 22),
  23: Lesson(4, 23),
  24: Lesson(4, 24),
  25: Lesson(4, 25),
  26: Lesson(4, 26),
  27: Lesson(5, 27),
  28: Lesson(5, 28),
  29: Lesson(5, 29),
  30: Lesson(5, 30),
  31: Lesson(5, 31),
  32: Lesson(5, 32),
  33: Lesson(5, 33),
  34: Lesson(5, 34),
  35: Lesson(5, 35),
  36: Lesson(6, 36),
  37: Lesson(6, 37),
  38: Lesson(6, 38),
  39: Lesson(6, 39),
  40: Lesson(6, 40),
  41: Lesson(6, 41),
  42: Lesson(6, 42),
  43: Lesson(7, 43),
  44: Lesson(7, 44),
  45: Lesson(7, 45),
  46: Lesson(7, 46),
  47: Lesson(7, 47),
  48: Lesson(7, 48),
  49: Lesson(7, 49),
  50: Lesson(7, 50),
  51: Lesson(8, 51),
  52: Lesson(8, 52),
  53: Lesson(8, 53),
  54: Lesson(8, 54),
  55: Lesson(8, 55),
  56: Lesson(8, 56),
  57: Lesson(9, 57),
  58: Lesson(9, 58),
  59: Lesson(9, 59),
  60: Lesson(9, 60),
  61: Lesson(9, 61),
  62: Lesson(9, 62),
  63: Lesson(9, 63),
  64: Lesson(10, 64),
  65: Lesson(10, 65),
  66: Lesson(10, 66),
  67: Lesson(10, 67),
  68: Lesson(10, 68),
};
final Map<int, Lesson> htmlLessons = {
  1: Lesson(1, 1),
  2: Lesson(1, 2),
  3: Lesson(1, 3),
  4: Lesson(1, 4),
  5: Lesson(1, 5),
  6: Lesson(1, 6),
  7: Lesson(1, 7),
  8: Lesson(1, 8),
  9: Lesson(2, 9),
  10: Lesson(2, 10),
  11: Lesson(2, 11),
  12: Lesson(2, 12),
  13: Lesson(2, 13),
  14: Lesson(2, 14),
  15: Lesson(2, 15),
  16: Lesson(3, 16),
  17: Lesson(3, 17),
  18: Lesson(3, 18),
  19: Lesson(3, 19),
  20: Lesson(3, 20),
  21: Lesson(3, 21),
  22: Lesson(3, 22),
  23: Lesson(3, 23),
  24: Lesson(3, 24),
  25: Lesson(4, 25),
  26: Lesson(4, 26),
  27: Lesson(4, 27),
  28: Lesson(4, 28),
  29: Lesson(4, 29),
  30: Lesson(4, 30),
  31: Lesson(4, 31),
  32: Lesson(5, 32),
  33: Lesson(5, 33),
  34: Lesson(5, 34),
  35: Lesson(5, 35),
  36: Lesson(5, 36),
  37: Lesson(5, 37),
  38: Lesson(5, 38),
  39: Lesson(6, 39),
  40: Lesson(6, 40),
  41: Lesson(6, 41),
  42: Lesson(6, 42),
  43: Lesson(6, 43),
  44: Lesson(6, 44),
  45: Lesson(6, 45),
  46: Lesson(6, 46),
  47: Lesson(6, 47),
  48: Lesson(7, 48),
  49: Lesson(7, 49),
  50: Lesson(7, 50),
  51: Lesson(7, 51),
  52: Lesson(7, 52),
  53: Lesson(7, 53),
  54: Lesson(7, 54),
};

final Map<String, Map<int, Lesson>> lessons = {
  "python": pythonLessons,
  "java": javaLessons,
  "basic": basicLessons,
  "dart": dartLessons,
  "html": htmlLessons,
};

class Lesson {
  final int moduleId;
  final int id;

  Lesson(this.moduleId, this.id);

  @override
  String toString() {
    return 'Lesson{moduleId: $moduleId, id: $id}';
  }
}
